/*

Auto-generated file by sb-mig discovery


Do not edit manually (use yarn components:discover instead)

*/
export const componentList = [
  'page',
  'settings',
  'sb-accordion-flex-group',
  'sb-accordion-item',
  'sb-accordion-section',
  'sb-accordion',
  'sb-animated-icon',
  'sb-blockquote-flex-group',
  'sb-blockquote-section',
  'sb-blockquote',
  'sb-breadcrumbs',
  'sb-button-group-flex-group',
  'sb-button-group-section',
  'sb-button-group',
  'sb-button',
  'sb-icon-button',
  'sb-link-button',
  'sb-modal-button',
  'sb-text-button',
  'sb-content-card-link',
  'sb-content-card-section',
  'sb-content-card',
  'sb-cta-card-section',
  'sb-cta-card',
  'sb-editorial-card-section',
  'sb-editorial-card',
  'sb-text-editorial-card-content',
  'sb-text-editorial-card-subtitle',
  'sb-card-body',
  'sb-card-subtitle',
  'sb-image-card',
  'sb-teaser-card-link',
  'sb-teaser-card-section',
  'sb-teaser-card',
  'sb-video-card-section',
  'sb-video-card',
  'sb-content-group-flex-group',
  'sb-content-group-section',
  'sb-content-group',
  'sb-divider-flex-group',
  'sb-divider-section',
  'sb-divider',
  'sb-flex-group-flex-group',
  'sb-flex-group-section',
  'sb-flex-group',
  'sb-icon-flex-group',
  'sb-icon',
  'sb-image-flex-group',
  'sb-image-section',
  'sb-image',
  'sb-link-flex-group',
  'sb-link-icon-animated',
  'sb-link-icon',
  'sb-link-text',
  'sb-link-tile-section',
  'sb-link-tile',
  'sb-link',
  'sb-list-flex-group',
  'sb-list-item',
  'sb-list',
  'sb-section-background-layer',
  'sb-section',
  'sb-surface-section',
  'sb-surface',
  'sb-table-section',
  'sb-table',
  'sb-tag-group',
  'sb-tag',
  'sb-body-text-flex-group',
  'sb-body-text-section',
  'sb-body-text',
  'sb-headline-flex-group',
  'sb-headline-section',
  'sb-headline',
  'sb-text-flex-group',
  'sb-text-section',
  'sb-text',
  'sb-social-embed',
  'sb-social-embed-section',
  'sb-social-embed-flex-group',
  'sb-video',
  'sb-video-section',
  'sb-carousel',
  'sb-card-carousel',
  'sb-carousel-section',
  'sb-card-carousel-section',
  'sb-tabs',
  'sb-tabs-section',
  'sb-tab-item',
  'sb-collapsible',
  'sb-collapsible-button',
  'sb-collapsible-content',
  'sb-collapsible-trigger',
  'sb-collapsible-section',
  'sb-collapsible-flex-group',
  'sb-position-layer',
] as const;

export type Components = (typeof componentList)[number];
